---
title: "R - Descriptive Statistics"
author: "Stephen Moore"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
    html_document:
        theme: default
        highlight: tango
        toc: true
---

### Introduction

This document demonstrates different ways of generating descriptive statistics and makes use of the diamonds dataset.

```{r init, warning=FALSE, message=FALSE}
library(knitr)
knitr::opts_chunk$set(tidy=T, 
               fig.width=10,
               fig.height=5,
               fig.align='left',
               warning=FALSE,
               message=FALSE,
               echo=TRUE)
options(width = 120)
library(dplyr)
library(ggplot2)
library(psych)
library(pastecs)
attach(diamonds)
```

### Base Package

```{r descriptiveStatistics1, tidy=F}
# show metadata for the dataset
str(diamonds)
# show the beginning and ending rows of the dataset
kable(head(diamonds), 
      format='markdown', 
      caption="Books Read",
      digits=4)
kable(tail(diamonds), 
      format='markdown', 
      caption="Books Read",
      digits=4)
```

```{r descriptiveStatistics2, tidy=F}
# show the mean of all variables in the dataset.
# This technique could also be used with other functions like
#   median()
#   sd()
#   min()
#   max()
numeric_columns = c(1,5:10)
sapply(diamonds[numeric_columns],mean,na.rm=T)
# show Tukey's five number summary (min, 1Q, median, 3Q, max)
fivenum(diamonds$price)
# base summary function; provides counts for categorical variables
summary(diamonds)
```

### psych Package

```{r descriptiveStatistics3, tidy=F}
# good alternative library for descriptive statistics
kable(describe(diamonds[numeric_columns]), 
      format='markdown', 
      caption="Books Read",
      digits=4)
describeBy(diamonds[numeric_columns], group=color)
```

### pastecs Package

```{r descriptiveStatistics4, tidy=F}
# another library
kable(stat.desc(diamonds[numeric_columns]), 
      format='markdown', 
      caption="Books Read",
      digits=4)
```

### dplyr Package

```{r descriptiveStatistics5, tidy=F}
# custom function for std err of the mean
se = function(x) {
  data = na.omit(x)
  sd(data) / sqrt(length(data)) 
}

# descriptive statistics
price_by_color = diamonds %>%
  group_by(color) %>% 
  summarise(ct=n(),
            mn=mean(price),
            md=median(price),
            min=min(price),
            max=max(price),
            range=max-min,
            sd=sd(price),
            se=se(price),
            skew=skew(price),
            kurtosis=kurtosi(price))
colnames(price_by_color) = 
  c('Color','Count','Mean','Median','Min','Max','Range','Std Dev','Std Err','Skew','Kurtosis')
kable(price_by_color, format='markdown', digits=4)

# percentiles
price_by_color_percentiles = diamonds %>%
    summarise('Min' = min(price),
              '10%' = quantile(price,prob=.10),
              '20%' = quantile(price,prob=.20),
              '30%' = quantile(price,prob=.30),
              '40%' = quantile(price,prob=.40),
              '50% / Median' = quantile(price,prob=.50),
              '60%' = quantile(price,prob=.60),
              '70%' = quantile(price,prob=.70),
              '80%' = quantile(price,prob=.80),
              '90%' = quantile(price,prob=.90),
              '95%' = quantile(price,prob=.95),
              'Max' = max(price))
kable(price_by_color_percentiles, format='markdown', digits=1)
```

### Programming Environment

```{r}
sessionInfo()
```


