---
title: "R Graphics - Histograms"
author: "Stephen Moore"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
    html_document:
        theme: default
        highlight: tango
        toc: true        
---

### Introduction

This document demonstrates different ways of generating histograms with the base, lattice and ggplot2 plotting packages.  Plots make use of the iris dataset.

```{r init, warning=FALSE, message=FALSE}
library(knitr)
knitr::opts_chunk$set(tidy=T, 
               fig.width=8,
               fig.height=6,
               fig.align='center',
               warning=FALSE,
               message=FALSE,
               echo=TRUE)
options(width = 120)
data(iris); attach(iris)
```

### Base Plotting Package

```{r basePlottingPackage1, tidy=F}
par(mfrow=c(1,3))
# frequencies with line for mean
hist(Sepal.Length, col="orange", 
     main="Sepal Length (Frequency)",
     xlab="Sepal Length (cm)")
abline(v=mean(Sepal.Length),col="blue",lwd=2)

# density with superimposed normal curve
hist(Sepal.Length, prob=TRUE, col="gray", 
     main="Sepal Length (Density)",
     xlab="Sepal Length (cm)",
     ylim=c(0.0,0.7))
curve(dnorm(x, mean=mean(Sepal.Length), sd=sd(Sepal.Length)), add=TRUE, col="purple")

# density with superimposed smoothed density curves; note how adjust parameter reveals
# multi-modal distribution
hist(Sepal.Length, prob=TRUE, col="violet", 
     main="Sepal Length (Density)",
     xlab="Sepal Length (cm)",
     ylim=c(0.0,0.7))
lines(density(Sepal.Length, adjust=0.50), col="red", lwd=2)
lines(density(Sepal.Length), col="blue", lwd=2)
lines(density(Sepal.Length, adjust=2), lty="dotted", col="darkgreen", lwd=2)
par(mfrow=c(1,1))
```

### Lattice Plotting Package

```{r latticePlottingPackage, tidy=F}
library(lattice)
histogram(~ Sepal.Length | Species,
          main="Sepal Length By Species",
          xlab="Sepal Length (cm)",
          breaks=seq(from=4,to=9,by=0.25),
          col=c("orange","lightblue","purple"),
          panel=function(x, col=col,...){
            panel.histogram(x,col=col[packet.number()],...)
          },
          layout=c(1,3))
densityplot(~ Sepal.Length | Species,
            main="Sepal Length By Species",
            xlab="Sepal Length (cm)",
            layout=c(1,3))
densityplot(~ Sepal.Length,
            groups=Species,
            xlab="Sepal Length (cm)",
            main="Sepal Length By Species",
            plot.points=FALSE,
            auto.key=TRUE)
```

### ggplot2 Plotting Package

```{r ggplot2PlottingPackage, tidy=F}
library(ggplot2)
library(ggthemes)
library(gridExtra)
ggplot(data = iris, aes(x=Sepal.Length,y=..density..)) +
  geom_histogram(fill="cornsilk",colour="grey60",size=.5) + 
  geom_line(stat="density", adjust=0.5, colour="red") +
  geom_line(stat="density") +
  geom_line(stat="density", adjust=2.0, colour="blue") +
  xlab("Sepal Length (cm)") +
  ylab("Density") +
  xlim(3,9) +
  theme_economist() +
  ggtitle("Sepal Length\n")
ggplot(data = iris, aes(x=Sepal.Length)) +
  geom_histogram(aes(fill=Species)) +
  scale_fill_brewer(palette="Set2") +
  facet_wrap( ~ Species, ncol=1) +
  xlab("Sepal Length (cm)") +
  ylab("Frequency") +
  xlim(3,9) +
  theme_bw() +
  ggtitle("Sepal Length By Species\n")
p1 = ggplot(data = iris, aes(x=Sepal.Length, colour=Species)) + 
    geom_line(stat="density") + 
    xlim(3,9) +
    xlab("Sepal Length (cm)") +
    ylab("Density")  + 
    ggtitle("Sepal Length By Species (Density)\n") +
    theme(plot.title = element_text(lineheight=.8, face="plain"))
p2 = ggplot(data = iris, aes(x=Sepal.Length, fill=Species)) + 
    geom_density(colour=NA,alpha=0.2) + 
    geom_line(stat="density") + 
    xlim(3,9) +
    xlab("Sepal Length (cm)") +
    ylab("Density")  + 
    ggtitle("Sepal Length By Species (Density)\n") +
    theme(plot.title = element_text(lineheight=.8, face="plain"))
grid.arrange(p1,p2,nrow=2)

p1 = ggplot(data = iris, aes(x=Sepal.Length, fill=Species)) +
  geom_bar()+
  xlab("Sepal Length (cm)") +
  ylab("Frequency") +
  ggtitle("Sepal Length By Species\n") +
  theme_bw()
p2 = ggplot(data = iris, aes(x=Sepal.Length, fill=Species)) +
  geom_bar(position="fill")+
  xlab("Sepal Length (cm)") +
  ylab("Frequency") +
  ggtitle("Sepal Length By Species\n") +
  theme_bw()
grid.arrange(p1,p2,nrow=2)
```

### Programming Environment

```{r}
sessionInfo()
```


