---
title: "R Graphics - Scatter Plots"
author: "Stephen Moore"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
    html_document:
        theme: default
        highlight: tango
---

### Introduction

This document demonstrates different ways of generating scatter plots with the base, CAR, lattice and ggplot2 plotting packages.  Plots make use of the iris dataset.

```{r init, warning=FALSE, message=FALSE}
library(knitr)
knitr::opts_chunk$set(tidy=T, 
               fig.width=5,
               fig.height=5,
               fig.align='left',
               warning=FALSE,
               message=FALSE,
               echo=TRUE)
options(width = 120)
library(ggplot2)
attach(iris)
```

### Base Plotting Package

```{r basePlottingPackage, tidy=F}
plot(Sepal.Length, Petal.Length,
     main="Flower Characteristics in Iris",
     xlab="Sepal Length",
     ylab="Petal Length",
     pch=16, cex=1,
     col=Species)
legend(x=4.5, y=7,
       legend=levels(Species),
       col=c(1:3),
       pch=16)
abline(lm(Petal.Length ~ Sepal.Length), col="purple")
lines(lowess(Sepal.Length, Petal.Length), col="blue")
```

### CAR Package

```{r carsPlottingPackage, tidy=F}
# Enhanced Scatterplot of MPG vs. Weight 
# by Number of Car Cylinders 
library(car) 
scatterplot(Sepal.Length ~ Petal.Length | Species, data=iris,
            main="Flower Characteristics in Iris",
            xlab="Sepal Length",
            ylab="Petal Length",
            labels=row.names(iris),
            legend.coords = "topleft")
```
```{r carsPlottingPackage2, fig.height=8, fig.width=8, tidy=F}
scatterplotMatrix(~ Petal.Length + Petal.Width + Sepal.Length + Sepal.Width | Species,
                   data=iris,
  	               main="Flower Characteristics in Iris",
                   legend.pos="bottomright")
```

#### Correlation Matrix

```{r correlationMatrix1, tidy=F}
kable(cor(iris[1:4]), 
      format='markdown', 
      caption="Correlation Matrix",
      digits=4)
```

### Lattice Plotting Package

```{r latticePlottingPackage, fig.height=8, fig.width=8,tidy=F}
# Scatterplot Matrices from the lattice Package 
library(lattice)
super.sym <- trellis.par.get("superpose.symbol")
splom(~iris[1:4], groups = Species, data = iris,
      panel = panel.superpose,
      key = list(title = "Flower Characteristics in Iris",
                 columns = 3, 
                 points = list(pch = super.sym$pch[1:3],
                 col = super.sym$col[1:3]),
                 text = list(c("setosa", "versicolor", "virginica"))))
```

### ggplot2 Plotting Package

```{r ggplot2PlottingPackage, tidy=F}
ggplot(iris,aes(x=Petal.Width,y=Petal.Length,shape=Species,colour=Species)) +
  geom_point() +
  xlab("Petal Width (cm)") +
  ylab("Petal Length (cm)") +
  theme_bw() +
  ggtitle("Flower Characteristics in Iris\n")

ggplot(iris,aes(x=Petal.Width,y=Petal.Length)) +
  geom_point(colour="purple") +
  xlab("Petal Width (cm)") +
  ylab("Petal Length (cm)") +
  theme_bw() +
  ggtitle("Flower Characteristics in Iris\n") +
  stat_smooth()
```

### Programming Environment

```{r}
sessionInfo()
```


